-- Find total customers by countries

SELECT
	country,
	COUNT(customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


SELECT
	country,
	COUNT(DISTINCT customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender

SELECT
	gender,
	COUNT(DISTINCT customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


-- Find total products by category

SELECT 
	category,
	COUNT(DISTINCT product_id) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;


-- What is the average costs in each category? 

SELECT
	category,
	ROUND(AVG(COALESCE(cost,0)),2) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?

SELECT
	dp.category,
	SUM(fa.sales_amount) AS total_revenue_category
FROM gold.fact_sales fa
LEFT JOIN gold.dim_products dp
	ON fa.product_key = dp.product_key
GROUP BY dp.category
ORDER BY total_revenue_category DESC;

-- Find total revenue is generated by each customer

SELECT
	fa.customer_key,
	dc.first_name,
	dc.last_name,
	SUM(fa.sales_amount) AS total_revenue_customer
FROM gold.fact_sales fa
LEFT JOIN gold.dim_customers dc
	ON fa.customer_key=dc.customer_key
GROUP BY fa.customer_key,dc.first_name,dc.last_name
ORDER BY total_revenue_customer DESC;

-- What is the distribution of sold items across countries?

-- country + SUM(quantity)
SELECT 
	dc.country,
	SUM(quantity) AS total_sold_items
FROM gold.fact_sales fa
LEFT JOIN gold.dim_customers dc
	ON dc.customer_key=fa.customer_key
GROUP BY dc.country
ORDER BY total_sold_items DESC;











